# This is a config for E2B sandbox template.
# You can use template ID (braz34razsiyq70hwt9b) or template name (nextjs-ryogan) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs-ryogan") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-ryogan") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-ryogan')

team_id = "917838ac-df52-4bfa-9ce4-ab71eb34f2c2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-ryogan"
template_id = "braz34razsiyq70hwt9b"
